development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: HDH
  pool: 5
  username: root
  password: root
  host: localhost
  socket: /Applications/MAMP/tmp/mysql/mysql.sock


test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: HDH_TEST
  pool: 5
  username: root
  password: root
  host: localhost
